### PR TITLE
Updating owners and upgrading to version and dependencies to go 1.18

### PR DESCRIPTION
**Pull request by MitaliBhalla**
This PR serves the purpose of updating the owners as well as upgrading to minimum go version as 1.18 , along with updating the required dependencies.

### CODE REVIEW

**Comment by MitaliBhalla** [comment]
@T0MASD I am trying to fix errors while bumping version to 1.18, but the pieplines show something about using 1.16 only, can you please help to take a look? Thanks.
cc : @supreeth7

**Comment by supreeth7** [comment]
The base image stream had to be updated, I've created https://github.com/openshift/release/pull/35289 to address it, PR checks should be good to go post that's merged.

**Comment by supreeth7** [comment]
@MitaliBhalla I'd like these two changes to be addressed in separate PRs.
I've created one (https://github.com/openshift/pagerduty-short-circuiter/pull/85) to solely bump `go` version without meddling with direct dependencies just yet as they would result in chained chaos, for example, the newer PD API has obsoleted a lot of fields we've used.
Could you please refactor this PR to only update the owners for now?

**Comment by MitaliBhalla** [comment]
Ack, thanks @supreeth7

**Comment by MitaliBhalla** [comment]
I am closing this PR as I have lot of changes pushed in this one.
Will create a fresh PR for updating owners.
cc : @T0MASD

**Pull request closed without merging**
