### PR TITLE
Updated Readme for pdcli oncall 

### PR DESCRIPTION
**Pull request by MitaliBhalla**

### CODE REVIEW

**Comment by supreeth7** [comment]
This will likely need further changes, let's wait for the initial doc updates to be completed first, you can add to that later.

**Comment by MitaliBhalla** [comment]
> This will likely need further changes, let's wait for the initial doc updates to be merged first, you can add to that later.

Ack

**Comment by supreeth7** [comment]
Please rebase and update the readme with oncall docs, make sure it's in the same format as alerts.

**Pull request closed without merging**
